// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace OUporabnikih.Migrations
{
    [DbContext(typeof(PodatkiDb))]
    [Migration("20240722063932_c")]
    partial class c
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("Registracije", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdTipa")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdUporabnika")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("Čas")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Registracija");
                });

            modelBuilder.Entity("Tipi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Vrsta");
                });

            modelBuilder.Entity("Uporabnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("HashiranoGeslo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("JeAktiven")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Ime")
                        .IsUnique();

                    b.ToTable("Uporabniki");
                });
#pragma warning restore 612, 618
        }
    }
}
