// <auto-generated />
using DelNaServerju;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DelNaServerju.Migrations
{
    [DbContext(typeof(PodatkiDb))]
    [Migration("20240730063914_a")]
    partial class a
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DelNaServerju.Kolo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdLastnika")
                        .HasColumnType("int");

                    b.Property<int>("LastnikId")
                        .HasColumnType("int");

                    b.Property<string>("Slika")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TrentnaLokacijaLatitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TrentnaLokacijaLongitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Znamka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LastnikId");

                    b.ToTable("Kolo");
                });

            modelBuilder.Entity("DelNaServerju.Uporabnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("JeAktiven")
                        .HasColumnType("bit");

                    b.Property<string>("KodiranoGeslo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Ime")
                        .IsUnique();

                    b.ToTable("Uporabniki");
                });

            modelBuilder.Entity("DelNaServerju.Kolo", b =>
                {
                    b.HasOne("DelNaServerju.Uporabnik", "Lastnik")
                        .WithMany()
                        .HasForeignKey("LastnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lastnik");
                });
#pragma warning restore 612, 618
        }
    }
}
